# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=200)),
                ('cuisine_slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_photo', models.ImageField(upload_to=b'/home/kishore/chai/smc/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_image', models.ImageField(upload_to=b'/home/kishore/chai/smc/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('full_address', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('name_slug', models.SlugField()),
                ('opening_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=200, null=True)),
                ('history', models.TextField(null=True)),
                ('cover_photo', models.ImageField(null=True, upload_to=b'/home/kishore/chai/smc/media/')),
                ('serves_alcohol', models.BooleanField(default=False)),
                ('non_veg', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=True)),
                ('air_conditioned', models.BooleanField(default=False)),
                ('out_seating', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('reservation', models.BooleanField(default=False)),
                ('catering', models.BooleanField(default=False)),
                ('cost_for_two', models.IntegerField(null=True)),
                ('cuisines', models.ManyToManyField(to='restaurant.Cuisine')),
                ('location', models.ManyToManyField(to='restaurant.Location')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_type',
            field=models.ManyToManyField(to='restaurant.RestaurantType'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='restaurant_photo_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurant.Restaurant'),
        ),
    ]
