# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20161226_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='geolocation',
            field=geoposition.fields.GeopositionField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='restaurant_photo',
            field=models.ImageField(upload_to=b'C:\\Users\\Pratik\\chai\\smc\\media/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(upload_to=b'C:\\Users\\Pratik\\chai\\smc\\media/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=b'C:\\Users\\Pratik\\chai\\smc\\media/'),
        ),
    ]
